# Generated by Django 4.2.5 on 2023-09-20 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_reserva_stand'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
