# Generated by Django 4.2.5 on 2023-09-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_reserva_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='created_at',
            new_name='data',
        ),
    ]
